"""Build the two SFB 1709 / Project B01 presentations (15 min + 5 min) as .pptx.

Single source of truth for every number and figure shown on a slide lives in the
constants block below, so the long talk and the lightning talk can never disagree.

Run:  uv pip install python-pptx  &&  .venv/bin/python scripts/build_presentations.py
Outputs: presentations/STAMP_B01_15min.pptx, presentations/STAMP_B01_5min.pptx

All figures are pulled from validation_report/. The script raises immediately if any
referenced figure is missing so a broken deck is never produced silently.
"""

from __future__ import annotations

import json
from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Emu, Inches, Pt

# --------------------------------------------------------------------------- #
# Paths
# --------------------------------------------------------------------------- #
ROOT = Path(__file__).resolve().parent.parent
VR = ROOT / "validation_report"
HEATMAPS = VR / "heatmaps"
PREP = VR / "preprocessing"
OUT_DIR = ROOT / "presentations"

S895 = HEATMAPS / "S_895 19 B Score 97 - 10 Fokuspunkte - entfettet - 2026-03-04 20.46.51"
S333 = HEATMAPS / "333 19 A Score 29 - 5 Fokuspunkte - entfettet - 2026-03-03 18.42.23"
PREP_127 = PREP / "127 26 C Score 0 - 5 Fokuspunkte - entfettet - 2026-03-04 17.28.20"

FIG = {
    "resp_pos": S333 / "response__overview.png",          # GT yes, P(yes)=0.945 -> correct
    "high_blast_pos": S895 / "high_blast__overview.png",  # GT yes, P(yes)=0.618 -> correct
    "blast_pct_fail": S895 / "blast_percent__overview.png",  # GT 75% -> pred 0.93%
    "prep_before": Path(str(PREP_127) + "__before.jpg"),
    "prep_after": Path(str(PREP_127) + "__after.jpg"),
    "prep_rejected": Path(str(PREP_127) + "__rejected_grid.jpg"),
    # cell-resolution (DeepHeme-style) pilot
    "cellres_positive": VR / "pilot_cell_res/positive/SAMPLE_395_486_19_A/contact_sheet.jpg",
    "cellres_failure": VR / "pilot_cell_res/failure/SAMPLE_396_803_19_B/contact_sheet.jpg",
    # blast-enrichment triage overlay (green = conservative cell-like candidates)
    "triage_overlay": VR / "blast_enrichment_triage/overlays/high_blast/"
    "SAMPLE_309_665_19_C__S_665_19_C_Score_95_-_10_Fokuspunkte_-_entfettet_-_2026-03-03_23.38.50/"
    "overlay_contact_sheet.jpg",
}

# Figures generated by scripts/build_presentation_assets.py (run that first).
ASSET = {name: OUT_DIR / "assets" / f"{name}.png" for name in (
    "fig_labels", "fig_cohort_cv", "fig_workflow", "fig_explain_enrichment",
    "exp_response", "exp_high_blast", "exp_blast_percent",
)}

# --------------------------------------------------------------------------- #
# Verified content (do not invent numbers — see plan / stats CSVs)
# --------------------------------------------------------------------------- #
TITLE = "Predicting VEN/AZA Response in AML from Blast Morphology with AI"
SUBTITLE = "SFB 1709 · Project B01  •  STAMP computational-pathology pipeline"
AUTHORS = "Jiefu Zhu (PhD)  •  PIs: Prof. J. N. Kather, Dr. M. Janssen"
AFFIL = "Dept. of Medical Oncology (NCT-HD) & Dept. of Hematology, Heidelberg University Hospital"
FOOTER = "SFB 1709 · B01 · STAMP"

# (task, type, n / split, AUROC or metric, note)
RESULTS_ROWS = [
    ("Task", "Type", "Samples", "Performance"),
    ("RESPONSE_CR (complete remission)", "binary", "489 (336 yes / 153 no)", "AUROC 0.870  (95% CI 0.80–0.94)"),
    ("HIGH_BLAST", "binary", "489 (98 / 391)", "AUROC 0.929  (0.88–0.98)"),
    ("BLAST_SEVERITY", "3-class", "489 (98 / 55 / 336)", "AUROC: high 0.91 · low 0.86 · interm. 0.78"),
    ("BLAST_PERCENT", "regression", "n≈97", "Pearson r 0.68 · R²≈0 · MAE 12%"),
]

TASKS_ROWS = [
    ("Label", "Question", "Type"),
    ("RESPONSE_CR", "Will the patient reach complete remission?", "binary (yes/no)"),
    ("HIGH_BLAST", "Is this a high-blast-burden sample?", "binary (yes/no)"),
    ("BLAST_SEVERITY", "Low / intermediate / high blast burden", "3-class"),
    ("BLAST_PERCENT", "What % of cells are blasts?", "regression (0–100)"),
]

# Colors
NAVY = RGBColor(0x1A, 0x4D, 0x8C)
DARK = RGBColor(0x22, 0x22, 0x22)
GREY = RGBColor(0x66, 0x66, 0x66)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
LIGHT = RGBColor(0xEE, 0xEF, 0xF7)

SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def _check_figs() -> None:
    missing = [str(p) for p in FIG.values() if not p.exists()]
    if missing:
        raise FileNotFoundError("Missing figures:\n  " + "\n  ".join(missing))


def _check_assets() -> None:
    missing = [str(p) for p in ASSET.values() if not p.exists()]
    if missing:
        raise FileNotFoundError(
            "Missing generated figures — run `python scripts/build_presentation_assets.py` first:\n  "
            + "\n  ".join(missing)
        )


def _blank(prs: Presentation):
    return prs.slides.add_slide(prs.slide_layouts[6])


def _footer(slide) -> None:
    box = slide.shapes.add_textbox(Inches(0.4), Inches(7.05), Inches(12.5), Inches(0.35))
    tf = box.text_frame
    tf.text = FOOTER
    p = tf.paragraphs[0]
    p.font.size = Pt(9)
    p.font.color.rgb = GREY


def _band(slide) -> None:
    """Thin navy accent bar under the title area."""
    bar = slide.shapes.add_shape(1, Inches(0.0), Inches(1.28), SLIDE_W, Pt(3))
    bar.fill.solid()
    bar.fill.fore_color.rgb = NAVY
    bar.line.fill.background()


def _title(slide, text: str) -> None:
    box = slide.shapes.add_textbox(Inches(0.5), Inches(0.35), Inches(12.3), Inches(0.9))
    tf = box.text_frame
    tf.word_wrap = True
    tf.text = text
    p = tf.paragraphs[0]
    p.font.size = Pt(28)
    p.font.bold = True
    p.font.color.rgb = NAVY
    _band(slide)


def add_title_slide(prs) -> None:
    slide = _blank(prs)
    bg = slide.shapes.add_shape(1, 0, 0, SLIDE_W, SLIDE_H)
    bg.fill.solid()
    bg.fill.fore_color.rgb = NAVY
    bg.line.fill.background()
    bg.shadow.inherit = False

    box = slide.shapes.add_textbox(Inches(0.8), Inches(2.1), Inches(11.7), Inches(2.0))
    tf = box.text_frame
    tf.word_wrap = True
    tf.text = TITLE
    p = tf.paragraphs[0]
    p.font.size = Pt(40)
    p.font.bold = True
    p.font.color.rgb = WHITE

    for txt, size in ((SUBTITLE, 20), (AUTHORS, 16), (AFFIL, 13)):
        b = slide.shapes.add_textbox(Inches(0.85), Inches(4.2 if size == 20 else (5.0 if size == 16 else 5.5)), Inches(11.6), Inches(0.6))
        t = b.text_frame
        t.word_wrap = True
        t.text = txt
        pr = t.paragraphs[0]
        pr.font.size = Pt(size)
        pr.font.color.rgb = RGBColor(0xDD, 0xE6, 0xF2)
    return slide


def set_notes(slide, text: str):
    """Attach speaker-notes (the spoken script) to a slide."""
    slide.notes_slide.notes_text_frame.text = text.strip()
    return slide


def _subtitle(slide, text: str) -> None:
    """Clean grey italic subtitle line just under the title band."""
    box = slide.shapes.add_textbox(Inches(0.55), Inches(1.36), Inches(12.3), Inches(0.5))
    tf = box.text_frame
    tf.word_wrap = True
    tf.text = text
    p = tf.paragraphs[0]
    p.font.size = Pt(14)
    p.font.italic = True
    p.font.color.rgb = GREY


def add_bullets(prs, title: str, bullets, *, tldr: str | None = None):
    """bullets: list of (text, level) or str (level 0). `tldr` renders as a clean subtitle."""
    slide = _blank(prs)
    _title(slide, title)
    top = Inches(1.6)
    if tldr:
        _subtitle(slide, tldr)
        top = Inches(2.05)

    box = slide.shapes.add_textbox(Inches(0.6), top, Inches(12.2), Inches(4.5))
    tf = box.text_frame
    tf.word_wrap = True
    first = True
    for item in bullets:
        text, level = item if isinstance(item, tuple) else (item, 0)
        p = tf.paragraphs[0] if first else tf.add_paragraph()
        first = False
        p.text = ("– " if level else "• ") + text
        p.level = level
        p.font.size = Pt(20 - 2 * level)
        p.font.color.rgb = DARK if level == 0 else GREY
        p.space_after = Pt(7)
    _footer(slide)
    return slide


def add_table(prs, title: str, rows, *, note: str | None = None, col_widths=None):
    slide = _blank(prs)
    _title(slide, title)
    n_rows, n_cols = len(rows), len(rows[0])
    width = Inches(12.3)
    height = Inches(0.55 * n_rows)
    gfx = slide.shapes.add_table(n_rows, n_cols, Inches(0.5), Inches(1.75), width, height)
    table = gfx.table
    if col_widths:
        for i, w in enumerate(col_widths):
            table.columns[i].width = Inches(w)
    for r, row in enumerate(rows):
        for c, val in enumerate(row):
            cell = table.cell(r, c)
            cell.text = str(val)
            para = cell.text_frame.paragraphs[0]
            para.font.size = Pt(15 if r else 15)
            if r == 0:
                para.font.bold = True
                para.font.color.rgb = WHITE
                cell.fill.solid()
                cell.fill.fore_color.rgb = NAVY
            else:
                para.font.color.rgb = DARK
                cell.fill.solid()
                cell.fill.fore_color.rgb = WHITE if r % 2 else LIGHT
    if note:
        nb = slide.shapes.add_textbox(Inches(0.5), Inches(1.85 + 0.55 * n_rows), Inches(12.3), Inches(1.2))
        tf = nb.text_frame
        tf.word_wrap = True
        tf.text = note
        pr = tf.paragraphs[0]
        pr.font.size = Pt(15)
        pr.font.italic = True
        pr.font.color.rgb = GREY
    _footer(slide)
    return slide


def _add_image_fit(slide, path: Path, left, top, max_w, max_h):
    """Insert image scaled to fit a box, preserving aspect ratio, centered."""
    from PIL import Image

    with Image.open(path) as im:
        iw, ih = im.size
    box_ratio = max_w / max_h
    img_ratio = iw / ih
    if img_ratio > box_ratio:
        w = max_w
        h = int(max_w / img_ratio)
    else:
        h = max_h
        w = int(max_h * img_ratio)
    off_l = left + (max_w - w) // 2
    off_t = top + (max_h - h) // 2
    slide.shapes.add_picture(str(path), Emu(off_l), Emu(off_t), width=Emu(w), height=Emu(h))


def add_image_slide(prs, title: str, fig: Path, caption: str, *, side_text=None, subtitle=None):
    slide = _blank(prs)
    _title(slide, title)
    img_top = Inches(1.65).emu
    if subtitle and not side_text:
        _subtitle(slide, subtitle)
        img_top = Inches(2.05).emu
    if side_text:
        # image left, text right
        _add_image_fit(slide, fig, Inches(0.5).emu, Inches(1.7).emu, Inches(7.4).emu, Inches(4.7).emu)
        tb = slide.shapes.add_textbox(Inches(8.2), Inches(1.8), Inches(4.7), Inches(4.6))
        tf = tb.text_frame
        tf.word_wrap = True
        first = True
        for item in side_text:
            text, level = item if isinstance(item, tuple) else (item, 0)
            p = tf.paragraphs[0] if first else tf.add_paragraph()
            first = False
            p.text = ("– " if level else "• ") + text
            p.level = level
            p.font.size = Pt(18 - 2 * level)
            p.font.color.rgb = DARK if level == 0 else GREY
            p.space_after = Pt(8)
        cap_top = Inches(6.5)
        cap_w = Inches(7.4)
        cap_left = Inches(0.5)
    else:
        _add_image_fit(slide, fig, Inches(0.5).emu, img_top, Inches(12.3).emu,
                       (Inches(6.55).emu - img_top))
        cap_top = Inches(6.65)
        cap_w = Inches(12.3)
        cap_left = Inches(0.5)
    cb = slide.shapes.add_textbox(cap_left, cap_top, cap_w, Inches(0.5))
    tf = cb.text_frame
    tf.word_wrap = True
    tf.text = caption
    pr = tf.paragraphs[0]
    pr.font.size = Pt(13)
    pr.font.italic = True
    pr.font.color.rgb = GREY
    _footer(slide)
    return slide


def add_two_image_slide(prs, title: str, left_fig, left_cap, right_fig, right_cap, *, banner=None):
    slide = _blank(prs)
    _title(slide, title)
    top = Inches(1.7).emu
    if banner:
        _subtitle(slide, banner)
        top = Inches(2.15).emu
    half = Inches(6.0).emu
    img_h = Inches(3.9).emu
    _add_image_fit(slide, left_fig, Inches(0.4).emu, top, half, img_h)
    _add_image_fit(slide, right_fig, Inches(6.9).emu, top, half, img_h)
    cap_top = Inches(6.35)
    for left_pos, cap in ((Inches(0.4), left_cap), (Inches(6.9), right_cap)):
        cb = slide.shapes.add_textbox(left_pos, cap_top, Inches(6.0), Inches(0.6))
        tf = cb.text_frame
        tf.word_wrap = True
        tf.text = cap
        pr = tf.paragraphs[0]
        pr.alignment = PP_ALIGN.CENTER
        pr.font.size = Pt(12)
        pr.font.italic = True
        pr.font.color.rgb = GREY
    _footer(slide)
    return slide


def add_section_end(prs, title: str, bullets):
    slide = _blank(prs)
    bg = slide.shapes.add_shape(1, 0, 0, SLIDE_W, SLIDE_H)
    bg.fill.solid()
    bg.fill.fore_color.rgb = NAVY
    bg.line.fill.background()
    tb = slide.shapes.add_textbox(Inches(0.8), Inches(0.7), Inches(11.7), Inches(1.0))
    tf = tb.text_frame
    tf.text = title
    tf.paragraphs[0].font.size = Pt(32)
    tf.paragraphs[0].font.bold = True
    tf.paragraphs[0].font.color.rgb = WHITE
    box = slide.shapes.add_textbox(Inches(0.9), Inches(2.0), Inches(11.5), Inches(4.6))
    tf = box.text_frame
    tf.word_wrap = True
    first = True
    for b in bullets:
        p = tf.paragraphs[0] if first else tf.add_paragraph()
        first = False
        p.text = "• " + b
        p.font.size = Pt(20)
        p.font.color.rgb = RGBColor(0xE6, 0xEC, 0xF5)
        p.space_after = Pt(12)
    return slide


# --------------------------------------------------------------------------- #
# 15-minute deck
# --------------------------------------------------------------------------- #
def build_15min() -> Presentation:
    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H

    add_title_slide(prs)

    # 2 Clinical motivation
    add_bullets(
        prs,
        "Clinical motivation",
        [
            "Acute myeloid leukemia (AML): aggressive blood cancer driven by immature blast cells.",
            "Venetoclax + azacitidine (VEN/AZA) is a key therapy — but response is variable and hard to predict up front.",
            "Blasts are the diagnostic read-out: counted and graded by hematopathologists on bone-marrow smears.",
            ("We study paired primary samples at diagnosis and relapse.", 1),
            "If blast morphology encodes who will respond, we can stratify patients earlier.",
        ],
        tldr="Goal: predict VEN/AZA response in AML directly from the appearance of blast cells.",
    )

    # 3 Project vision
    add_bullets(
        prs,
        "Project B01 — the vision",
        [
            "Analyze cytologic variability of AML blasts as a determinant of VEN/AZA response.",
            "Combine two modalities on the same patients:",
            ("Generative-AI / deep-learning image analysis of blast morphology (this talk).", 1),
            ("Single-cell RNA sequencing (scRNA-seq) of the same samples.", 1),
            "Integrate morphology + molecular profiles to predict outcome and discover novel response biomarkers.",
        ],
        tldr="B01: morphology (AI) + single-cell transcriptomics → response prediction & biomarker discovery.",
    )

    # 4 What is STAMP
    add_bullets(
        prs,
        "What is STAMP?",
        [
            "End-to-end, weakly-supervised deep-learning pipeline: whole-slide image → biomarker prediction.",
            "No pixel-level annotations needed — only one clinical label per sample.",
            "Peer-reviewed protocol (Nature Protocols 2024); used across many tumor types and centers.",
            "Supports 20+ pathology foundation models and classification, regression & survival in one framework.",
            ("We use it as the image-analysis engine for B01.", 1),
        ],
        tldr="STAMP turns gigapixel slides into predictions with only slide-level labels.",
    )

    # 5 Pipeline
    add_bullets(
        prs,
        "The STAMP pipeline (as we run it)",
        [
            "1.  Preprocess — tile each smear WSI into 224×224 patches; QC filters drop empty/blurred tiles.",
            "2.  Feature extraction — UNI2 pathology foundation model embeds every tile.",
            "3.  Aggregation — Vision-Transformer multiple-instance learning (MIL) pools tiles → one prediction per sample.",
            "4.  Cross-validation — 5-fold; every sample is predicted while held out of training.",
            "5.  Outputs — metrics with 95% CIs + explainability heatmaps + top-tile exports.",
        ],
        tldr="Preprocess → UNI2 tile features → ViT-MIL → 5-fold crossval → metrics + heatmaps.",
    )

    # 6 Cohort & labels
    add_bullets(
        prs,
        "Our cohort & labels",
        [
            "Bone-marrow smear whole-slide images from the AG Janssen AML cohort.",
            "69 patients • 489 samples (diagnosis/relapse × smear parts A/B/C) • 511 slide images.",
            "Tile features: UNI2 (uni2-0242c340). Model: ViT-MIL (dim 512, 2 layers, 8 heads), 5-fold crossval.",
            "Four clinical labels per sample, defined with the hematology team:",
            ("RESPONSE_CR, HIGH_BLAST, BLAST_SEVERITY, BLAST_PERCENT.", 1),
        ],
        tldr="69 patients • 489 samples • 511 BM-smear WSIs • 4 prediction tasks.",
    )

    # 7 The 4 tasks
    add_table(prs, "The four prediction tasks", TASKS_ROWS, col_widths=[2.9, 6.4, 3.0])

    # 8 Results at a glance
    add_table(
        prs,
        "Results at a glance (5-fold cross-validation)",
        RESULTS_ROWS,
        col_widths=[4.6, 1.7, 2.8, 3.2],
        note="Classification reported as cross-validated AUROC with 95% CI. Regression: correlation is "
        "strong but absolute calibration is poor (see BLAST_PERCENT slide).",
    )

    # 9 RESPONSE_CR
    add_image_slide(
        prs,
        "RESPONSE_CR — predicting complete remission",
        FIG["resp_pos"],
        "Heatmap: sample 333 19 A (held-out). GT = responder (yes); model P(yes)=0.945. "
        "Red = tiles most relevant to the 'responder' prediction.",
        side_text=[
            "AUROC 0.870 (95% CI 0.80–0.94).",
            "Best clinically actionable result: response is predictable from morphology alone.",
            "Heatmap shows the model concentrates on cell-rich smear regions.",
            ("Confident mistakes are flagged for re-review (label-noise check).", 1),
        ],
    )

    # 10 HIGH_BLAST
    add_image_slide(
        prs,
        "HIGH_BLAST — detecting high blast burden",
        FIG["high_blast_pos"],
        "Heatmap: sample S_895 19 B (held-out). GT = high blast (yes); model P(yes)=0.618 → correct.",
        side_text=[
            "AUROC 0.929 (95% CI 0.88–0.98) — our strongest classifier.",
            "Attention lands on dense blast-rich areas.",
            "This is the signal we trust most for visual triage.",
        ],
    )

    # 11 BLAST_SEVERITY
    add_bullets(
        prs,
        "BLAST_SEVERITY — low / intermediate / high",
        [
            "3-class severity grading.",
            "AUROC: high 0.912 • low 0.864 • intermediate 0.783.",
            ("The 'intermediate' class is hardest — expected, it sits between two boundaries.", 1),
            "High and low are separated reliably; intermediate is where extra annotation would help most.",
        ],
        tldr="Severity grading works well at the extremes; the middle class is the hard one.",
    )

    # 12 BLAST_PERCENT regression
    add_image_slide(
        prs,
        "BLAST_PERCENT — a cautionary result",
        FIG["blast_pct_fail"],
        "Regression relevance map: sample S_895 19 B. GT blast = 75%, but predicted 0.9% (|err| 74%).",
        side_text=[
            "Pearson r = 0.68 (p≈10⁻¹⁴): ranks samples well.",
            "But R²≈0 and MAE 12% — absolute values are mis-calibrated.",
            "Fails badly on the highest-blast slides.",
            ("Lesson: trust the ordering, not the exact % (yet).", 1),
        ],
    )

    # 13 Explainability & triage
    add_two_image_slide(
        prs,
        "What the model looks at — and what to trust",
        FIG["high_blast_pos"],
        "HIGH_BLAST attention — tracks clinical blast burden (proxy AUROC 0.86, ρ=0.35).",
        FIG["blast_pct_fail"],
        "BLAST_PERCENT relevance — does NOT track blast burden (proxy AUROC 0.42, ρ=−0.04).",
        banner="Same slide, two heads: use HIGH_BLAST maps for visual blast triage — not the regression maps.",
    )

    # 14 Preprocessing QC
    add_two_image_slide(
        prs,
        "Preprocessing QC insight: a data-quality finding",
        FIG["prep_before"],
        "Before — raw smear (sample 127 26 C).",
        FIG["prep_after"],
        "After — only 4.7% of tiles kept (green); rest dropped (red).",
        banner="Cause: out-of-focus tiles fail the Canny edge filter — a 5- vs 10-'Fokuspunkte' scan issue. Fix = re-scan.",
    )

    # 15 Toward annotation
    add_bullets(
        prs,
        "Toward hematopathologist annotation",
        [
            "We rank slides by how much a human label would help, in three buckets:",
            ("Confidently correct → validate the visual cues the model relies on.", 1),
            ("Confidently wrong → surface label noise or genuinely hard morphology (highest value).", 1),
            ("Near the decision boundary → add ground truth exactly where it moves AUROC.", 1),
            "Output is a ready-to-review deck + overlay contact sheets for the hematology team.",
        ],
        tldr="A targeted annotation plan turns model uncertainty into the most informative labels.",
    )

    # 16 Limitations
    add_bullets(
        prs,
        "Limitations",
        [
            "Labels are slide-level, not cell-level — no per-blast ground truth yet.",
            "BLAST_PERCENT regression is mis-calibrated on high-blast samples.",
            "Focus/staining artifacts (and the 5-Fokuspunkte scans) reduce usable tissue on some slides.",
            "Some confident errors look like label noise — needs pathologist adjudication.",
            "Single-center cohort; external validation still to come.",
        ],
    )

    # 17 Next steps + acknowledgments
    add_section_end(
        prs,
        "Summary & next steps",
        [
            "Response (AUROC 0.87) and blast burden (0.93) are predictable from smear morphology alone.",
            "Explainability heatmaps make the predictions auditable for clinicians.",
            "Next: pathologist annotation round, regression re-calibration, re-scan low-focus slides.",
            "Then: integrate with single-cell transcriptomics for VEN/AZA biomarker discovery.",
            "Thanks: AG Janssen, Kather Lab, SFB 1709 consortium.",
        ],
    )

    return prs


# --------------------------------------------------------------------------- #
# 5-minute deck
# --------------------------------------------------------------------------- #
def build_5min() -> Presentation:
    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H

    add_title_slide(prs)

    add_bullets(
        prs,
        "The question",
        [
            "AML is treated with venetoclax + azacitidine — but who responds is hard to predict.",
            "Blasts (leukemic cells) are graded by eye on bone-marrow smears.",
            "Can we predict VEN/AZA response directly from blast morphology?",
            ("Project B01: AI image analysis + single-cell transcriptomics on paired diagnosis/relapse samples.", 1),
        ],
        tldr="Predict VEN/AZA response in AML from the appearance of blast cells.",
    )

    add_bullets(
        prs,
        "Our approach",
        [
            "STAMP weakly-supervised pipeline on bone-marrow smear WSIs (only slide-level labels).",
            "UNI2 tile features → Vision-Transformer MIL → 5-fold cross-validation.",
            "69 patients • 489 samples • 511 slides • 4 prediction tasks.",
            "Outputs metrics with 95% CIs and explainability heatmaps.",
        ],
        tldr="Slide → UNI2 features → ViT-MIL → cross-validated prediction + heatmap.",
    )

    add_table(
        prs,
        "Key results (5-fold cross-validation)",
        RESULTS_ROWS,
        col_widths=[4.6, 1.7, 2.8, 3.2],
        note="Response and blast burden are strongly predictable. Blast-% regression ranks well "
        "(r=0.68) but is not yet calibrated (R²≈0, MAE 12%).",
    )

    add_image_slide(
        prs,
        "What the model looks at",
        FIG["resp_pos"],
        "RESPONSE_CR heatmap: sample 333 19 A (held-out). GT responder; P(yes)=0.945. "
        "Red = most relevant tiles — the prediction is auditable.",
        side_text=[
            "Heatmaps localize the morphology driving each call.",
            "HIGH_BLAST attention tracks clinical blast burden.",
            ("Caveat: trust blast-% ordering, not the exact number.", 1),
        ],
    )

    add_section_end(
        prs,
        "Takeaways",
        [
            "Response (AUROC 0.87) & high blast burden (0.93) predictable from smear morphology alone.",
            "Predictions are explainable via heatmaps — ready for clinician review.",
            "Next: pathologist annotation + integration with single-cell transcriptomics for biomarkers.",
        ],
    )

    return prs


# --------------------------------------------------------------------------- #
# Full project-review deck (~15-18 min) WITH speaker notes (spoken script)
# --------------------------------------------------------------------------- #
EXP_ROADMAP_ROWS = [
    ("#", "Experiment", "What we asked"),
    ("1", "RESPONSE_CR", "Predict complete remission from the smear"),
    ("2", "HIGH_BLAST", "Flag high blast burden"),
    ("3", "BLAST_SEVERITY", "Grade blast burden (low/interm./high)"),
    ("4", "BLAST_PERCENT", "Regress the exact % of blasts"),
    ("5", "Explainability + triage", "Do the heatmaps point at real blasts?"),
    ("6", "Preprocessing / data QC", "Why do some slides lose most tiles?"),
    ("7", "Cell-resolution pilot", "Can a human even see cells in our tiles?"),
]


def _load_metrics():
    f = OUT_DIR / "assets" / "metrics.json"
    return json.loads(f.read_text()) if f.exists() else None


def _hide(slide):
    """Mark a slide hidden in the linear slideshow (appendix / backup)."""
    slide._element.set("show", "0")
    return slide


ANALYSIS = {name: OUT_DIR / "assets" / f"{name}.png" for name in (
    "fig_sample_vs_patient", "fig_auprc_calibration",
    "fig_response_beyond_blast", "fig_confounder",
)}


def build_project_review() -> Presentation:
    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H

    M = _load_metrics()
    missing = [str(p) for p in ANALYSIS.values() if not p.exists()]
    if M is None or missing:
        raise FileNotFoundError(
            "Run `python scripts/build_analysis_figs.py` (after training) first — "
            "missing metrics.json and/or analysis figures:\n  " + "\n  ".join(missing))

    P, S = M["patient"], M["sample"]

    def clf(m):
        return f"AUROC {m['auroc']:.2f} (95% CI {m['lo']:.2f}–{m['hi']:.2f})"

    resp_drop = S["response"]["auroc"] - P["response"]["auroc"]
    hb_drop = S["high_blast"]["auroc"] - P["high_blast"]["auroc"]
    sev = P["blast_severity"]["per_class"]
    conf = M["confounder"]

    results_rows = [
        ("Task", "Type", "n", "Patient-level result (5-fold CV)"),
        ("RESPONSE_CR", "binary", "489", clf(P["response"])),
        ("HIGH_BLAST", "binary", "489", clf(P["high_blast"])),
        ("BLAST_SEVERITY", "3-class", "489", f"macro-AUROC {P['blast_severity']['auroc']:.2f}"),
        ("BLAST_PERCENT", "regression", "489",
         f"Pearson r {P['blast_percent']['pearson']:.2f} · R² {P['blast_percent']['r2']:.2f} · MAE {P['blast_percent']['mae']:.0f}%"),
    ]

    # 1 Title
    set_notes(
        add_title_slide(prs),
        "Good morning, and thank you for the time. I'll present our progress on Project B01 — "
        "predicting venetoclax–azacitidine response in AML from bone-marrow smear morphology with "
        "deep learning. I'll cover the clinical question, our data, the method, all the experiments, "
        "the honest cross-validated results, and where I'd like your input.",
    )

    # 2 Clinical problem
    set_notes(
        add_bullets(prs, "Clinical problem", [
            "AML is an aggressive leukemia driven by immature blast cells.",
            "Venetoclax + azacitidine (VEN/AZA) is a standard therapy, but response is heterogeneous.",
            "Predicting response before treatment remains an unmet need.",
            "Blasts are assessed manually on bone-marrow smears — informative but subjective and slide-level.",
        ], tldr="Question: can treatment response be predicted from blast morphology?"),
        "AML is driven by immature cells called blasts. Venetoclax plus azacitidine is a standard "
        "therapy, but response varies a lot between patients and is hard to predict up front. Blasts "
        "are already read on smears, so there is rich morphological information — it is just "
        "subjective and summarised at the slide level. Our question: is that morphology enough to "
        "predict response?",
    )

    # 3 Project approach
    set_notes(
        add_bullets(prs, "Project B01: approach", [
            "Hypothesis: cytologic variability of blasts encodes treatment response.",
            "Two modalities on paired diagnosis/relapse samples:",
            ("Computational image analysis of blast morphology (this work).", 1),
            ("Single-cell RNA sequencing of the same samples.", 1),
            "Aim: predict response and identify candidate VEN/AZA biomarkers.",
        ], tldr="Image morphology + single-cell transcriptomics, integrated on the same patients."),
        "The hypothesis is that blast morphology carries response information. The project pairs two "
        "modalities on the same diagnosis and relapse samples — image analysis, which I'll show "
        "today, and single-cell RNA sequencing. The aim is prediction and, by linking the two, "
        "candidate biomarkers of VEN/AZA response.",
    )

    # 4 Cohort & CV design
    set_notes(
        add_image_slide(prs, "Cohort and cross-validation design", ASSET["fig_cohort_cv"],
            "69 patients · 489 bone-marrow samples · 511 slide images. Because there are ~7 smears "
            "per patient, folds must be grouped by patient (next slide).",
            subtitle="Weakly supervised — one clinical label per sample, no cell-level annotation."),
        "The cohort is 69 patients, 489 samples across 511 slides. The crucial detail for evaluation "
        "is that there are about seven smears per patient — up to 24 for one patient. That shapes how "
        "we must cross-validate, which is the next slide.",
    )

    # 5 Evaluation methodology (leakage + fix)
    set_notes(
        add_bullets(prs, "Evaluation: avoiding data leakage", [
            "RESPONSE_CR is a patient-level outcome, copied onto all ~7 of a patient's smears.",
            "If folds split by sample, a patient's other smears can sit in training while one is tested — leakage.",
            "Fix: group folds by PATIENT (StratifiedGroupKFold) — no patient spans train and test.",
            f"Effect is real: sample-split vs patient-grouped AUROC differs by "
            f"{resp_drop:+.2f} (RESPONSE_CR) and {hb_drop:+.2f} (HIGH_BLAST).",
            "All results shown here are patient-grouped.",
        ], tldr="We re-ran every task with patient-grouped CV; the honest numbers follow."),
        "A methodological point I want to be transparent about. Response is a patient-level outcome, "
        "so it is the same label on all of a patient's smears. If we split folds by sample, the model "
        "can see other smears from the same patient during training and then be tested on a held-out "
        "smear of that same patient — that is leakage, and it inflates performance. So I re-ran all "
        "four tasks grouping the folds by patient, which guarantees no patient is in both train and "
        "test. Everything I show from here on is the honest, patient-grouped evaluation.",
    )

    # 6 Label distribution
    set_notes(
        add_image_slide(prs, "Clinical label distribution", ASSET["fig_labels"],
            "Classes are imbalanced (98/489 high-blast; most samples <5% blasts) — we report AUROC, "
            "AUPRC and calibration accordingly.",
            subtitle="Four prediction targets derived from the clinical table."),
        "The four targets and their distributions. Two points: the classes are imbalanced — only "
        "about 98 of 489 samples are high-blast — and blast percentage is concentrated below 5% with "
        "a long high tail. That tail is where the regression struggles.",
    )

    # 7 Method
    set_notes(
        add_image_slide(prs, "Method: the STAMP pipeline", ASSET["fig_workflow"],
            "Tile + QC each slide; embed tiles with the UNI2 foundation model; aggregate with an "
            "attention Transformer (MIL); heatmaps expose the evidence.",
            subtitle="WSI → tiling + QC → UNI2 tile features → ViT-MIL aggregation → patient-grouped CV."),
        "The method is the published STAMP pipeline. Slides are tiled and quality-filtered, every "
        "tile is embedded by the UNI2 foundation model, and an attention Transformer aggregates them "
        "into one prediction per sample. The attention gives us heatmaps, which matter for the "
        "interpretability experiment.",
    )

    # 8 Experiments overview
    set_notes(
        add_table(prs, "Experiments", EXP_ROADMAP_ROWS, col_widths=[0.7, 4.3, 7.3]),
        "Here is the full set of experiments — four predictive models, an interpretability test, a "
        "preprocessing-quality investigation, and a cell-level feasibility pilot. I'll take them in order.",
    )

    # 9 Honest results headline
    set_notes(
        add_image_slide(prs, "Results: honest (patient-grouped) evaluation", ANALYSIS["fig_sample_vs_patient"],
            "Grey = leaky sample-split; navy = patient-grouped. The patient-grouped bars are the "
            "numbers we stand behind.",
            subtitle="Fixing the leakage lowers the estimates but the ranking of tasks is preserved."),
        "This is the headline. The grey bars are the old sample-split numbers; the navy bars are the "
        "honest patient-grouped numbers. Performance comes down when we remove the leakage — as "
        "expected, most for response — but the picture is stable: high blast burden is easiest, "
        "response is predictable above chance, and blast percentage stays the weak spot. These navy "
        "numbers are what we stand behind.",
    )

    # 10 Results table (patient-level)
    set_notes(
        add_table(prs, "Results at a glance (patient-grouped, 5-fold CV)", results_rows,
                  col_widths=[3.6, 1.8, 1.2, 6.7],
                  note="Classification: AUROC with 95% CI. Regression: correlates but is not calibrated."),
        "The same numbers in a table. I'll now walk through each experiment with the supporting heatmaps.",
    )

    # 11 Exp1 RESPONSE
    set_notes(
        add_image_slide(prs, "Experiment 1 — Complete-remission label (RESPONSE_CR)", ASSET["exp_response"],
            "Two held-out cases (left non-responder, right responder). Top: whole-slide image; bottom: "
            "attention on cellular smear regions. (Illustrative maps from the initial models.)",
            subtitle=f"Patient-grouped {clf(P['response'])}  —  but note the caveat on the labels (slide 17)."),
        "Experiment one is the complete-remission label. The honest patient-grouped AUROC is "
        f"{P['response']['auroc']:.2f}. I'll show it here, but with an important caveat I'll come back "
        "to in a few slides: in this dataset the RESPONSE_CR label turns out to be defined by the "
        "blast count, so this number is closely tied to blast burden rather than an independent "
        "outcome. The heatmaps, from the initial models, show attention on the cellular smear.",
    )

    # 12 Exp2 HIGH_BLAST
    set_notes(
        add_image_slide(prs, "Experiment 2 — High blast burden (HIGH_BLAST)", ASSET["exp_high_blast"],
            "Three held-out high-blast cases; attention overlaps the dense blast clusters in the WSIs above.",
            subtitle=f"Patient-grouped {clf(P['high_blast'])} — the strongest classifier."),
        f"Experiment two, high blast burden — our strongest model at AUROC {P['high_blast']['auroc']:.2f}, "
        "and it barely moves under patient-grouped CV, which makes sense because blast burden is "
        "genuinely visible in the images. The attention lands on the dense blast clusters. This is the "
        "signal we trust most.",
    )

    # 13 Exp3 SEVERITY
    set_notes(
        add_bullets(prs, "Experiment 3 — Blast-severity grading (3-class)", [
            "Three-class grade: low / intermediate / high.",
            f"Patient-grouped one-vs-rest AUROC: high {sev.get('high', float('nan')):.2f} · "
            f"low {sev.get('low', float('nan')):.2f} · intermediate {sev.get('intermediate', float('nan')):.2f}.",
            ("Extremes separate reliably; the intermediate band is hardest.", 1),
            "Indicates where additional expert annotation would help most.",
        ], tldr="Reliable at the extremes; the intermediate class is the main source of error."),
        "Experiment three grades severity into three levels. High and low are recovered well; the "
        "intermediate band is hardest, which matches clinical experience — the middle is genuinely "
        "ambiguous. That tells us where extra annotation would pay off.",
    )

    # 14 Exp4 BLAST_PERCENT
    set_notes(
        add_image_slide(prs, "Experiment 4 — Blast-percentage regression", ASSET["exp_blast_percent"],
            "Prediction heatmaps: the model attends to blast-rich regions but under-predicts the count "
            "on high-blast slides (e.g. 90% → 12%).",
            subtitle=f"Pearson r {P['blast_percent']['pearson']:.2f}, R² {P['blast_percent']['r2']:.2f}, "
                     f"MAE {P['blast_percent']['mae']:.0f}% — good ranking, poor calibration."),
        f"Experiment four, the exact blast percentage. Correlation is moderate — Pearson "
        f"{P['blast_percent']['pearson']:.2f} — so ordering is roughly right, but calibration is poor: "
        "it systematically under-predicts the highest-blast slides, as in these examples where the "
        "truth is 90% and the model says about 12%. Use the ranking, not the absolute number.",
    )

    # 15 Exp5 Explainability
    set_notes(
        add_image_slide(prs, "Experiment 5 — Does attention localise real blasts?", ASSET["fig_explain_enrichment"],
            "Overlap of top-attended regions with cell-rich tissue by clinical blast band, over ~490 "
            "samples. HIGH_BLAST attention rises with blast burden; BLAST_PERCENT attention does not.",
            subtitle="HIGH_BLAST maps track clinical blasts (proxy AUROC 0.86); regression maps do not (0.42)."),
        "Experiment five asks whether the attention is trustworthy, across all samples. For the "
        "HIGH_BLAST model, the overlap of top-attended regions with cell-rich tissue rises with blast "
        "burden — proxy AUROC 0.86. For the regression model it is flat, no better than chance. So we "
        "use the HIGH_BLAST maps for visual triage, not the regression maps.",
    )

    # 16 AUPRC + calibration
    set_notes(
        add_image_slide(prs, "Precision-recall and calibration", ANALYSIS["fig_auprc_calibration"],
            "Patient-grouped RESPONSE_CR and HIGH_BLAST. PR curves address the class imbalance; "
            "reliability curves show how well probabilities are calibrated.",
            subtitle="Beyond AUROC: performance under imbalance, and probability calibration."),
        "Because AUROC can look optimistic under class imbalance, here are precision-recall curves and "
        "calibration. HIGH_BLAST holds up well on precision-recall; response is weaker, consistent "
        "with the AUROC. The reliability curves show where the probabilities are well-calibrated and "
        "where they'd need adjustment before any clinical use.",
    )

    # 17 What RESPONSE_CR actually measures (important caveat)
    set_notes(
        add_image_slide(prs, "Important caveat: what RESPONSE_CR actually measures", ANALYSIS["fig_response_beyond_blast"],
            "In this table, every <5%-blast sample is labelled 'responder' and every ≥5% sample "
            "'non-responder' — RESPONSE_CR is exactly the <5%-blast (morphologic-CR) criterion.",
            subtitle="RESPONSE_CR ≡ blast < 5% here, so the 'response' model is re-reading blast burden, "
                     "not an independent treatment outcome."),
        "This is the most important caveat, and I want to be upfront about it. When I split the "
        "response labels by blast burden, the separation is perfect: every sample under 5% blasts is "
        "labelled responder, and every sample at or above 5% is non-responder. In other words, "
        "RESPONSE_CR as provided is exactly the morphologic complete-remission criterion — marrow "
        "blasts under 5%. So the 0.83 'response' number is the model re-reading blast burden on the "
        "same slide, not predicting an independent treatment outcome. A genuine response-prediction "
        "task needs the outcome decoupled from the same-slide blast count — for example predicting "
        "later response from the diagnostic smear. I flag this clearly and it's my first question for "
        "the clinical team.",
    )

    # 18 Confounder
    set_notes(
        add_image_slide(prs, "Batch-effect check: scan protocol", ANALYSIS["fig_confounder"],
            "Left: is the scan protocol (5 vs 10 focus points) associated with the label? Right: can "
            "the model's score predict the protocol? A high AUROC here would be a red flag.",
            subtitle=f"Score-predicts-protocol AUROC = {conf['protocol_from_score_auroc']:.2f} "
                     f"(0.5 = no batch signal)."),
        "Kather will ask about batch effects, so I checked directly. On the left, whether the scan "
        "protocol is associated with the label; on the right, whether the model's score can predict "
        f"the protocol — that AUROC is {conf['protocol_from_score_auroc']:.2f}. The closer to 0.5, the "
        "less the model is keying on scanner batch rather than biology. I'll also add stain "
        "normalization as a safeguard.",
    )

    # 19 Preprocessing QC
    set_notes(
        add_two_image_slide(prs, "Experiment 6 — Preprocessing quality investigation",
            FIG["prep_before"], "Before — raw smear (sample 127 26 C); tissue is present.",
            FIG["prep_after"], "After — only 4.7% of tiles retained (green kept, red dropped).",
            banner="Cause: out-of-focus tiles fail the focus filter — the 5- vs 10-Fokuspunkte scan setting. Fix: re-scan."),
        "Experiment six: some slides lose almost all tiles in preprocessing — this one kept under 5%. "
        "The tissue is present; the tiles fail the focus filter, not the background filter, and it "
        "tracks the scan setting. The pipeline is behaving correctly; the fix is upstream — re-scan "
        "those slides at higher focus.",
    )

    # 20 Cell-resolution pilot
    set_notes(
        add_image_slide(prs, "Experiment 7 — Cell-resolution feasibility pilot", FIG["cellres_positive"],
            "Model-selected tiles + centred zooms for one high-blast case; assembled for "
            "hematopathologist review.",
            side_text=[
                "Can individual cells be resolved in the tiles the model selects?",
                "A prerequisite check before any cell-level (DeepHeme-style) model.",
                "12-slide deck: 5 regression failures, 4 high-blast, 3 low-blast.",
                ("Uses existing native-resolution tiles; no new training.", 1),
                ("Status: assembled; awaiting pathologist read-out.", 1),
            ]),
        "The last experiment is forward-looking. Before investing in a cell-level method like "
        "DeepHeme, we need to know whether a human can resolve individual cells in the tiles our model "
        "selects. So I assembled a twelve-slide review deck from the native-resolution tiles the "
        "pipeline already exports. It's ready for a hematopathologist to score, which is where I'd "
        "value the team's help.",
    )

    # 21 Findings
    set_notes(
        add_bullets(prs, "Summary of findings", [
            f"The models reliably read blast burden from morphology: HIGH_BLAST AUROC "
            f"{P['high_blast']['auroc']:.2f}, robust to the leakage fix.",
            "Caveat: RESPONSE_CR ≡ blast <5% here, so it is not yet an independent treatment outcome.",
            "Attention is interpretable: HIGH_BLAST maps localise blast-rich tissue.",
            "Blast-% regression ranks but is not calibrated — use ordering only.",
            "No strong scanner-batch confound (protocol-from-score AUROC 0.59); focus is a fixable bottleneck.",
        ], tldr="Robust, interpretable blast-burden reading; the 'response' label needs decoupling from blast count."),
        "Pulling it together: the strong, honest result is that the model reliably reads blast burden "
        "from morphology, and that holds up under patient-grouped evaluation. The key caveat is that "
        "the response label, as provided, is the blast-count criterion, so we can't yet call it "
        "treatment-response prediction. The models are interpretable, the regression ranks but isn't "
        "calibrated, there's no strong scanner-batch confound, and focus quality is fixable.",
    )

    # 22 Limitations
    set_notes(
        add_bullets(prs, "Limitations", [
            "RESPONSE_CR label ≡ blast <5% — reflects the CR criterion, not an independent outcome.",
            "Labels are slide-level; no cell-level ground truth yet.",
            "Blast-% regression is mis-calibrated on high-blast samples.",
            "Some confident errors may be label noise — need pathologist adjudication.",
            "Single-center cohort; external validation pending.",
        ]),
        "Limitations. Labels are slide-level. The percentage regression is mis-calibrated. The "
        "subgroup analyses are limited by small numbers. Some confident errors may be label noise. And "
        "this is a single center — external validation is still ahead.",
    )

    # 23 Next steps
    set_notes(
        add_bullets(prs, "Proposed next steps", [
            "Immediate: confirm RESPONSE_CR definition; obtain an outcome decoupled from same-slide blast count.",
            "Short term: hematopathologist review of the 12-slide pilot and the confident-error list.",
            "Short term: re-scan low-focus slides at full focus and re-run those samples.",
            "Medium: recalibrate/reframe blast-% (ordinal); annotate the intermediate band; add stain normalization.",
            "Long term: integrate morphology with single-cell RNA-seq for biomarkers; external validation.",
        ], tldr="Immediate priority: pin down the response label, then pathologist review + re-scan."),
        "Proposed next steps, and where I'd like your input. Short term: a pathologist review of the "
        "pilot and the confident-error list, and re-scanning the low-focus slides. Medium term: "
        "recalibrate the blast-percentage task, annotate the intermediate band, add stain "
        "normalization, and build a small cell-level annotation set. Long term: integrate with the "
        "single-cell data for biomarkers and validate externally. My immediate ask is the pathologist "
        "review and the re-scan.",
    )

    # 24 Closing
    set_notes(
        add_bullets(prs, "Summary", [
            f"Honest, patient-grouped: morphology reads blast burden well (HIGH_BLAST {P['high_blast']['auroc']:.2f}).",
            "Key caveat surfaced: RESPONSE_CR ≡ blast <5% — decouple the outcome before claiming response prediction.",
            "Interpretable, auditable predictions; no strong scanner-batch confound.",
            "Clear next actions: confirm labels, pathologist review, re-scan, recalibrate, annotate.",
            "Next horizon: morphology + single-cell transcriptomics for VEN/AZA biomarkers.",
        ], tldr="Thank you — I welcome your feedback and questions."),
        "In summary: the honest, robust result is that morphology reads blast burden well and it holds "
        "under patient-grouped evaluation. The most important thing I surfaced is that the response "
        "label here is the blast-count criterion, so decoupling the outcome is the first priority. The "
        "models are interpretable, I've checked the confounds, and the exciting direction is "
        "integrating with the single-cell data. Thank you — I welcome your feedback and questions.",
    )

    # ---------------- Appendix (hidden backup slides for the 10-min Q&A) -----
    _hide(set_notes(add_bullets(prs, "Appendix — backup slides", [
        "Patient- vs sample-level leakage detail",
        "Full metrics table (sample vs patient, all tasks)",
        "RESPONSE_CR definition checklist",
        "Anticipated questions",
    ], tldr="Reference material for discussion."),
        "These are backup slides for the discussion."))

    _hide(set_notes(add_bullets(prs, "Appendix — why sample-split leaks", [
        "69 patients but 489 samples: mean 7.1, max 24 smears per patient.",
        "RESPONSE_CR is one outcome per patient, copied to every smear of that patient.",
        "Sample-split CV puts a patient's other smears in training → memorisation, not generalisation.",
        f"Result: AUROC inflated by {resp_drop:+.2f} (RESPONSE_CR), {hb_drop:+.2f} (HIGH_BLAST).",
        "Patient-grouped StratifiedGroupKFold removes it; every sample still predicted once.",
    ]), "Detail on the leakage and the fix."))

    full_rows = [("Task", "Sample-split", "Patient-grouped")]
    for t, nm in [("response", "RESPONSE_CR"), ("high_blast", "HIGH_BLAST")]:
        full_rows.append((nm, clf(S[t]), clf(P[t])))
    full_rows.append(("BLAST_SEVERITY (macro)",
                      f"AUROC {S['blast_severity']['auroc']:.2f}", f"AUROC {P['blast_severity']['auroc']:.2f}"))
    full_rows.append(("BLAST_PERCENT",
                      f"r {S['blast_percent']['pearson']:.2f}, R² {S['blast_percent']['r2']:.2f}",
                      f"r {P['blast_percent']['pearson']:.2f}, R² {P['blast_percent']['r2']:.2f}"))
    _hide(set_notes(add_table(prs, "Appendix — full metrics (sample vs patient)", full_rows,
                              col_widths=[3.4, 4.9, 4.9]),
        "Full comparison table for reference."))

    _hide(set_notes(add_bullets(prs, "Appendix — RESPONSE_CR definition (to confirm)", [
        "Confirm: complete-remission criteria (ELN 2022?) and assessment timepoint.",
        "Confirm: which smear (diagnosis vs relapse) each label attaches to.",
        "Confirm: handling of patients with multiple timepoints in the outcome.",
        "These affect interpretation and are needed before any clinical claim.",
    ]), "Checklist of label-definition questions to resolve with the clinical team."))

    _hide(set_notes(add_bullets(prs, "Appendix — anticipated questions (1/2)", [
        "Leakage: addressed — all numbers are patient-grouped.",
        "Imbalance: see PR/calibration slide; AUROC + AUPRC both reported.",
        "Is 'response' just blast burden? Yes here — RESPONSE_CR ≡ blast <5% (CR criterion); needs decoupling.",
        "Batch effects: protocol-from-score AUROC 0.59 (mild); stain-normalization planned.",
    ]), "Q&A crib — methodology."))

    _hide(set_notes(add_bullets(prs, "Appendix — anticipated questions (2/2)", [
        "Why UNI2 / this model? Default; foundation-model & aggregator ablations planned.",
        "Clinical utility? Proof of concept; needs calibration + external validation.",
        "Why smears vs flow? Cheap, routine, preserves single-cell morphology (orthogonal signal).",
        "scRNA-seq integration: correlate attention regions / image features with cell states & response.",
    ]), "Q&A crib — clinical & next steps."))

    return prs


def main() -> None:
    _check_figs()
    _check_assets()
    OUT_DIR.mkdir(exist_ok=True)
    out15 = OUT_DIR / "STAMP_B01_15min.pptx"
    out5 = OUT_DIR / "STAMP_B01_5min.pptx"
    out_review = OUT_DIR / "STAMP_B01_project_review.pptx"
    build_15min().save(out15)
    build_5min().save(out5)
    build_project_review().save(out_review)
    for p in (out15, out5, out_review):
        kb = p.stat().st_size / 1024
        print(f"wrote {p}  ({kb:.0f} KB)")


if __name__ == "__main__":
    main()
